id = "adonix4gl-lang"
name = "Adonix 4GL"
version = "0.0.1"
schema_version = 1
authors = ["Jacob Spreitzer"]
description = "Support for Adonix 4GL."
repository = "https://github.com/SpreitzerJacobGit/adonix4gl-zed-lang"

[grammars.adonix4gl]
repository = "https://github.com/SpreitzerJacobGit/tree-sitter-adonix4gl"
rev = "bed2780b672ef303ec878a23de48c56f4385d3ce"
